// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAD1TLTFpSUSgV8h_aJPAm4A1QZ1b3_dI',
    appId: '1:960080017218:web:4da253e95d843f1451fadb',
    messagingSenderId: '960080017218',
    projectId: 'fir-teste-40346',
    authDomain: 'fir-teste-40346.firebaseapp.com',
    storageBucket: 'fir-teste-40346.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEfN4DtKZQH73gswVZhF15e-K9qZEOY78',
    appId: '1:960080017218:android:30fb19a128d1cea451fadb',
    messagingSenderId: '960080017218',
    projectId: 'fir-teste-40346',
    storageBucket: 'fir-teste-40346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm6vZVxE_WI3l1trZIG9WiJDtBmjNWylY',
    appId: '1:960080017218:ios:323a1d6829804e8251fadb',
    messagingSenderId: '960080017218',
    projectId: 'fir-teste-40346',
    storageBucket: 'fir-teste-40346.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm6vZVxE_WI3l1trZIG9WiJDtBmjNWylY',
    appId: '1:960080017218:ios:968dfe79a4e7de3651fadb',
    messagingSenderId: '960080017218',
    projectId: 'fir-teste-40346',
    storageBucket: 'fir-teste-40346.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
